const List = ({ items }) => <ul className="check-list">{items.map(item => <li key={item}>{item}</li>)}</ul>
const Link = ({ href, children }) => <a href={href} target="_blank" rel="noreferrer">{children} ↗</a>

export const sharePointToc = [
  ['tujuan', 'Tujuan pembelajaran'], ['ringkasan', 'Ringkasan eksekutif'], ['profil', 'Profil kerentanan'],
  ['alur', 'Alur rantai serangan'], ['status', 'Status eksploitasi'], ['sistem', 'Sistem berisiko'],
  ['dampak', 'Dampak potensial'], ['indikator', 'Indikator pemeriksaan'], ['mitigasi', 'Mitigasi dan pembaruan'],
  ['respons', 'Respons insiden'], ['pelajaran', 'Pelajaran utama'], ['evaluasi', 'Pertanyaan evaluasi'],
]

const profileRows = [
  ['Jenis', 'Authentication bypass', 'Remote code execution'], ['Komponen', 'Validasi JWT SharePoint', 'Business Connectivity Services'],
  ['Akar masalah', 'Kelemahan pipeline validasi token', 'Instansiasi tipe .NET tidak aman'], ['Akses awal', 'Jaringan, tanpa autentikasi', 'Akses ke fungsi BCS tertentu'],
  ['Dampak sendiri', 'Menyamar sebagai pengguna atau administrator', 'Kode berjalan sebagai akun layanan'], ['Dampak jika dirangkai', 'Akses terautentikasi palsu', 'Mengubah akses palsu menjadi RCE'],
  ['Status PoC', 'Tersedia secara publik', 'Tersedia secara publik'], ['Perbaikan', 'Pembaruan Juli 2026 atau lebih baru', 'Pembaruan Agustus 2026'],
]

export default function SharePointAttackChain() {
  return <>
    <section id="tujuan"><p className="step-label">01 · MATERI KEAMANAN SIBER</p><h2>Tujuan pembelajaran</h2><p>Setelah mempelajari materi ini, peserta diharapkan mampu:</p><List items={['Menjelaskan fungsi CVE-2026-55040 dan CVE-2026-63520.', 'Memahami bagaimana dua kerentanan dirangkai menjadi unauthenticated remote code execution.', 'Mengidentifikasi SharePoint yang berpotensi terdampak.', 'Menentukan langkah deteksi, mitigasi, patching, dan respons insiden.', 'Membedakan proof-of-concept, percobaan eksploitasi, dan eksploitasi berhasil.']} /></section>

    <section id="ringkasan"><p className="step-label">02</p><h2>Ringkasan eksekutif</h2><p><strong>CVE-2026-55040</strong> memungkinkan authentication bypass melalui kelemahan validasi JSON Web Token (JWT). <strong>CVE-2026-63520</strong> memungkinkan eksekusi kode melalui instansiasi tipe .NET yang tidak aman pada Business Connectivity Services (BCS).</p><p>Jika digabungkan, penyerang dari jaringan dapat menyamar sebagai pengguna berprivilege, mengakses fungsi administratif SharePoint, lalu menjalankan kode dengan hak akun layanan SharePoint.</p><div className="risk-box"><span>Cakupan utama</span><strong>SharePoint Server on-premises</strong><p>SharePoint Online yang dioperasikan Microsoft tidak termasuk cakupan. Rapid7 menyatakan CVE-2026-63520 memengaruhi seluruh versi SharePoint Server yang masih didukung. <Link href="https://www.rapid7.com/blog/post/ve-cve-2026-55040-microsoft-sharepoint-jwt-token-authentication-bypass-fixed/">Analisis authentication bypass</Link> · <Link href="https://www.rapid7.com/blog/post/etr-cve-2026-63520-microsoft-sharepoint-remote-code-execution-fixed/">Analisis RCE</Link></p></div></section>

    <section id="profil"><p className="step-label">03</p><h2>Profil kerentanan</h2><div className="article-table-wrap" tabIndex="0" role="region" aria-label="Profil kerentanan"><table className="article-table"><caption>Perbandingan dua kerentanan</caption><thead><tr><th>Aspek</th><th>CVE-2026-55040</th><th>CVE-2026-63520</th></tr></thead><tbody>{profileRows.map(row => <tr key={row[0]}><th scope="row">{row[0]}</th><td>{row[1]}</td><td>{row[2]}</td></tr>)}</tbody></table></div>
      <h3>CVE-2026-55040: authentication bypass</h3><p>JWT SharePoint untuk autentikasi service-to-service semestinya hanya diterima jika penerbit, sertifikat, dan tanda tangan kriptografinya tepercaya. Analisis Rapid7 menemukan kelemahan yang saling memperkuat:</p><List items={['Persyaratan token bertanda tangan tidak diterapkan dengan benar.', 'Resolusi sertifikat actor token tanpa validasi tanda tangan memadai.', 'Validasi penerbit dapat menerima sertifikat tidak terdaftar.', 'Pemeriksaan tanda tangan tidak memberi validasi kriptografis sebagaimana diharapkan.']} /><p>Token palsu dapat diperlakukan sebagai token sah dan dipakai untuk bertindak sebagai pengguna atau administrator. CVSS 3.1 kerentanan ini adalah <strong>9,1 (Critical)</strong>. <Link href="https://www.rapid7.com/blog/post/ra-microsoft-sharepoint-jwt-token-authentication-bypass-cve-2026-55040/">Analisis teknis Rapid7</Link></p>
      <h3>CVE-2026-63520: remote code execution</h3><p>BCS menghubungkan SharePoint dengan sumber data atau komponen eksternal. Pada versi rentan, definisi tipe .NET dari model BCS dapat diinstansiasi tanpa pembatasan cukup kuat. Penyerang dengan akses yang dibutuhkan dapat memicu eksekusi kode dengan hak akun layanan SharePoint. Dampak bergantung pada privilege akun, akses jaringan, izin basis data, dan pemisahan hak.</p>
    </section>

    <section id="alur"><p className="step-label">04</p><h2>Alur rantai serangan</h2><div className="attack-chain">{['Penyerang tanpa autentikasi', 'JWT palsu diterima', 'Akses berprivilege', 'Penyalahgunaan BCS', 'Kode berjalan sebagai akun layanan'].map((step, i) => <div key={step}><span>{i + 1}</span><strong>{step}</strong></div>)}</div><ol className="material-numbered"><li>Penyerang menemukan SharePoint Server yang dapat dijangkau.</li><li>Validasi JWT yang lemah digunakan untuk memperoleh identitas palsu.</li><li>Identitas itu membuka fungsi yang biasanya memerlukan privilege.</li><li>BCS digunakan untuk mencapai instansiasi tipe .NET rentan.</li><li>Jika berhasil, kode berjalan dengan hak akun layanan.</li></ol><div className="safe-note"><strong>Mengapa harus dirangkai?</strong><p>CVE-2026-55040 sendiri tidak langsung memberi shell. CVE-2026-63520 juga tidak otomatis menjadi unauthenticated RCE tanpa jalur menuju fungsi rentan.</p></div></section>

    <section id="status"><p className="step-label">05</p><h2>Status eksploitasi terkini</h2><p>Pada 25 Agustus 2026, honeypot mendeteksi authentication bypass, lalu enumerasi administratif dan probing Business Data Catalog. Belum ditemukan eksekusi kode berhasil pada honeypot tersebut.</p><div className="risk-box"><span>Kesimpulan yang tepat</span><strong>Rangkaian sedang diuji atau diprobel</strong><p>Bukti tersebut belum menunjukkan seluruh rantai berhasil menguasai server. Namun, CVE-2026-55040 telah dilaporkan mengalami weaponization setelah PoC dipublikasikan. <Link href="https://www.bleepingcomputer.com/news/security/hackers-target-microsoft-sharepoint-rce-chain-with-poc-exploit/">Perkembangan eksploitasi</Link> · <Link href="https://www.vulncheck.com/blog/cve-2026-63520-sharepoint-unsafe-type-rce">Riset VulnCheck</Link></p></div></section>

    <section id="sistem"><p className="step-label">06</p><h2>Sistem yang berisiko</h2><List items={['SharePoint Server Subscription Edition, 2019, dan 2016.', 'Server yang dapat diakses langsung dari internet.', 'Server dengan BCS atau Business Data Catalog aktif.', 'Farm tanpa pembaruan Juli dan Agustus 2026.', 'Akun layanan SharePoint dengan hak berlebihan.', 'Server dengan konektivitas bebas ke database, domain controller, file server, atau internet.']} /><div className="safe-note"><strong>SharePoint Online tidak termasuk cakupan</strong><p>Layanan tersebut dikelola dan diperbarui Microsoft.</p></div></section>

    <section id="dampak"><p className="step-label">07</p><h2>Dampak potensial</h2><List items={['Pengambilalihan SharePoint serta pencurian dokumen dan informasi sensitif.', 'Perubahan atau penghapusan konten.', 'Eksekusi perintah sebagai akun layanan.', 'Pencurian kredensial dan konfigurasi farm.', 'Lateral movement dan penanaman persistensi.', 'Gangguan layanan, kerusakan integritas data, atau ransomware.']} /><p>Hak administrator lokal atau domain yang luas pada akun layanan dapat mengubah kompromi satu server menjadi kompromi jaringan.</p></section>

    <section id="indikator"><p className="step-label">08</p><h2>Indikator dan aktivitas yang perlu diperiksa</h2><p>Belum ada satu indikator kompromi universal. Korelasikan pola heuristik berikut.</p><h3>Log web dan IIS</h3><List items={['Bearer token atau JWT tidak lazim dari IP eksternal.', 'Peningkatan request ke endpoint administratif.', 'Aktivitas tidak wajar pada client.svc atau ProcessQuery.', 'Percobaan berulang diikuti enumerasi situs, pengguna, atau hak.', 'Perubahan atau unggahan model Business Data Catalog yang tidak lazim.']} /><h3>Aktivitas proses</h3><List items={['w3wp.exe atau layanan SharePoint membuat child process tidak semestinya.', 'cmd.exe, powershell.exe, cscript.exe, wscript.exe, atau utilitas jaringan menjadi child process layanan web.', 'Executable atau script dibuat di direktori temporer.', 'Koneksi keluar berasal dari proses SharePoint.', 'Akun layanan dipakai untuk aktivitas interaktif.']} /><h3>Perubahan sistem</h3><List items={['Administrator baru atau permission berubah tanpa tiket.', 'Model BCS, library, atau koneksi data tidak dikenal.', 'Scheduled task, service, autorun, atau konfigurasi baru.', 'Perubahan IIS dan web application.', 'Akses tidak lazim ke configuration atau content database.']} /><p><strong>Satu temuan tidak otomatis membuktikan eksploitasi;</strong> kombinasi temuan memerlukan investigasi.</p></section>

    <section id="mitigasi"><p className="step-label">09</p><h2>Mitigasi dan pembaruan</h2><div className="article-table-wrap" tabIndex="0" role="region" aria-label="Pembaruan Agustus 2026"><table className="article-table"><caption>Pembaruan keamanan Agustus 2026</caption><thead><tr><th>Produk</th><th>Pembaruan</th></tr></thead><tbody><tr><th>Subscription Edition</th><td><Link href="https://support.microsoft.com/en-us/servicing/office/hotfix/august/5002893">KB5002893</Link>, build 16.0.19725.20522</td></tr><tr><th>SharePoint 2019</th><td><Link href="https://support.microsoft.com/en-us/servicing/office/hotfix/august/5002894">KB5002894</Link></td></tr><tr><th>SharePoint 2016</th><td><Link href="https://support.microsoft.com/help/5002905">KB5002905</Link>, build 16.0.5561.1001</td></tr></tbody></table></div><p>Microsoft menonaktifkan impor model BDC berbasis file secara default. Jangan aktifkan kembali tanpa kebutuhan bisnis dan penilaian risiko.</p><h3>Langkah mitigasi prioritas</h3><ol className="material-numbered">{['Inventarisasi seluruh server, versi, build, dan pembaruannya.', 'Pasang pembaruan Juli 2026 untuk CVE-2026-55040.', 'Pasang pembaruan Agustus 2026 untuk CVE-2026-63520.', 'Perbarui seluruh node farm, bukan hanya front-end.', 'Batasi akses melalui VPN, reverse proxy, atau allowlist.', 'Nonaktifkan BCS dan impor model BDC jika tidak digunakan.', 'Terapkan least privilege pada akun layanan.', 'Pantau child process IIS dan SharePoint.', 'Sentralisasikan IIS, ULS, Windows Event, EDR, firewall, dan proxy log.'].map(x => <li key={x}>{x}</li>)}</ol></section>

    <section id="respons"><p className="step-label">10</p><h2>Respons apabila server diduga disusupi</h2><p>Patching saja tidak menghapus persistensi yang mungkin telah dibuat penyerang.</p>{[['Containment', ['Batasi akses internet tanpa mematikan server jika bukti volatile diperlukan.', 'Blokir artefak tervalidasi dan cegah komunikasi lateral akun layanan.']], ['Pengumpulan bukti', ['Amankan IIS, ULS, Windows Event, EDR, firewall, WAF, dan database audit log.', 'Ambil forensic image, dokumentasikan waktu, proses, koneksi, task, service, dan akun baru.']], ['Eradikasi', ['Terapkan patch dan hapus artefak setelah didokumentasikan.', 'Rotasi password dan secret; cabut sesi, token, serta sertifikat dicurigai.']], ['Pemulihan', ['Pulihkan dari sumber bersih bila integritas tidak terjamin dan uji farm.', 'Perketat monitoring, lakukan post-incident review, serta perbaiki segmentasi dan privilege.']]].map(([title, items], i) => <div className="response-stage" key={title}><h3>Tahap {i + 1} — {title}</h3><List items={items} /></div>)}</section>

    <section id="pelajaran"><p className="step-label">11</p><h2>Pelajaran utama</h2><List items={['Kerentanan berbeda dapat jauh lebih berbahaya ketika dirangkai.', 'Authentication bypass dapat membuka kerentanan pascaautentikasi.', 'Sistem yang sudah dipatch belum tentu bersih.', 'Pantau aplikasi internet-facing berdasarkan perilaku, bukan hanya CVE.', 'Least privilege membatasi dampak RCE.', 'PoC publik memperpendek waktu menuju percobaan eksploitasi.']} /></section>

    <section id="evaluasi"><p className="step-label">12</p><h2>Pertanyaan evaluasi</h2><ol className="material-numbered">{['Apa fungsi CVE-2026-55040?', 'Mengapa CVE-2026-63520 tidak selalu menjadi unauthenticated RCE sendiri?', 'Apa beda probing dan eksploitasi berhasil?', 'Mengapa akun layanan perlu least privilege?', 'Mengapa patching saja tidak cukup?', 'Produk SharePoint mana yang menjadi fokus?', 'Aktivitas proses apa yang menandakan RCE?'].map(x => <li key={x}>{x}</li>)}</ol><details className="answer-key"><summary>Kunci jawaban singkat</summary><ol className="material-numbered"><li>Melewati autentikasi lewat kelemahan validasi JWT.</li><li>Masih diperlukan akses ke fungsi BCS rentan.</li><li>Probing adalah percobaan; keberhasilan memerlukan bukti dampak.</li><li>Agar kompromi tidak memberi hak terlalu luas.</li><li>Persistensi mungkin sudah dibuat.</li><li>SharePoint Server on-premises yang masih didukung.</li><li>Child process mencurigakan dari w3wp.exe atau layanan SharePoint.</li></ol></details></section>
  </>
}
