<?php
declare(strict_types=1);
$config=require dirname(__DIR__).'/config/config.php';$db=new PDO($config['dsn'],$config['user'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
$catalog=[
['web','Web Exploitation','</>',['Cookie Crumbs','Robots Whisper','Header Inspector','Broken Access Map','Template Echo','Session Switchboard','Archive Traversal','Blind Ledger','CSP Labyrinth','Citadel Zero']],
['crypto','Cryptography','⌘',['Caesar Dispatch','Base Camp 64','XOR Lantern','Vigenere Postcard','Hash Detective','Padding Signals','Nonce Reuse','RSA Common Ground','Elliptic Footprints','Quantumless Vault']],
['forensics','Digital Forensics','◉',['Deleted Memo','Metadata Trail','Browser Breadcrumbs','Memory Strings','Timeline Drift','Packet Evidence','Registry Shadow','Volatile Beacon','Disk Mosaic','Incident Blackbox']],
['reverse','Reverse Engineering','⇄',['Strings Attached','Branch Compass','License Routine','Packed Greeting','Bytecode Diary','Android Gate','Anti-Debug Alley','Firmware Maze','Obfuscated Engine','Phoenix Core']],
['binary','Binary Exploitation','01',['Stack Postcard','Format Telescope','Integer Wrap','Return Address','Canary Workshop','Heap Tags','ROP Steps','Race Window','Allocator Mirage','Fortress Process']],
['osint','OSINT','⌕',['Image Landmark','Username Constellation','Document Provenance','Map Shadow','Domain History','Code Trail','Certificate Atlas','Supply Chain Map','Campaign Timeline','Phantom Organization']],
['network','Network Security','⌁',['DNS Footprints','Handshake Reader','Port Story','ARP Theatre','TLS Inspector','Routing Detour','Beacon Rhythm','Tunnel Vision','Segmentation Escape','Zero Trust Siege']],
['stego','Steganography','▧',['Pixel Corners','Audio Specter','Trailing Bytes','Palette Secret','Waveform Ink','Whitespace Morse','Layered Canvas','Frequency Vault','Polyglot Portrait','Invisible Gallery']],
['linux','Linux and Privilege Escalation','$_',['Permission Trail','Cron Notes','SUID Compass','Path Hijack Lab','Service Papers','Capability Climb','Container Boundary','Namespace Passage','Kernel Clues','Rootless Summit']],
['misc','Miscellaneous Security','✦',['QR Fragments','Log Correlation','Token Anatomy','Cloud Policy','Supply Chain Receipt','Mobile Backup','Smart Contract Trace','Threat Model Chess','Detection Engineering','Pegasus Grand Prix']]];
$verbs=['identifikasi indikator tersembunyi','rekonstruksi urutan kejadian','verifikasi kelemahan konfigurasi','korelasikan artefak terisolasi','urai transformasi berlapis','petakan trust boundary','buktikan dampak secara aman','bangun jalur analisis','validasi hipotesis insiden','gabungkan seluruh teknik arena'];$artifacts=['catatan HTTP','arsip simulasi','capture laboratorium','image disk sintetis','binary latihan','snapshot sandbox','dataset publik sintetis','rekaman protokol','media buatan','konfigurasi container'];
$db->beginTransaction();$cat=$db->prepare('INSERT INTO ctf_categories(slug,name,description,icon,is_linear) VALUES(?,?,?,?,1) ON DUPLICATE KEY UPDATE name=VALUES(name),description=VALUES(description),icon=VALUES(icon),id=LAST_INSERT_ID(id)');$ch=$db->prepare('INSERT INTO ctf_challenges(public_id,category_id,prerequisite_id,title,slug,difficulty,scenario,learning_objective,flag_hash,solution,references_json,base_points,max_attempts,time_limit_minutes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,20,60) ON DUPLICATE KEY UPDATE title=VALUES(title),scenario=VALUES(scenario),learning_objective=VALUES(learning_objective),solution=VALUES(solution),references_json=VALUES(references_json),id=LAST_INSERT_ID(id)');$hint=$db->prepare('INSERT INTO ctf_hints(challenge_id,hint_order,content,penalty_percent) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE content=VALUES(content),penalty_percent=VALUES(penalty_percent)');$secrets=[];$n=0;
foreach($catalog as [$slug,$name,$icon,$titles]){$cat->execute([$slug,$name,"Arena $name berisi sepuluh investigasi progresif pada aset simulasi milik PEGASUS.",$icon]);$cid=(int)$db->lastInsertId();$previous=null;foreach($titles as $i=>$title){$n++;$difficulty=$i<3?'easy':($i<7?'medium':($i<9?'hard':'expert'));$points=['easy'=>100,'medium'=>200,'hard'=>350,'expert'=>500][$difficulty];$token=strtolower($slug).'_'.str_pad((string)($i+1),2,'0',STR_PAD_LEFT).'_'.bin2hex(random_bytes(5));$flag="PEGASUS{{$token}}";$scenario="Misi $title: tim SOC menerima {$artifacts[($i+$cid)%count($artifacts)]} dari range $name yang sengaja dikonfigurasi untuk latihan. Operator harus {$verbs[$i]} tanpa koneksi ke target eksternal.";$objective="Setelah misi $title, peserta mampu menjelaskan bukti, metode verifikasi, risiko, dan satu mitigasi untuk teknik $name tingkat $difficulty.";$solution="Pembahasan $title: inventarisasi resource read-only, buat hash kerja, cari anomali yang relevan dengan tujuan, korelasikan bukti secara berurutan, lalu ekstrak token dari artefak final. Validasi temuan tanpa menjalankan input tak tepercaya pada host dan catat mitigasi defensif.";$refs=json_encode([["label"=>"OWASP / NIST learning reference for $name","url"=>"https://www.nist.gov/cyberframework"]],JSON_THROW_ON_ERROR);$public='PG-'.str_pad((string)$n,6,'0',STR_PAD_LEFT);$ch->execute([$public,$cid,$previous,$title,"$slug-".($i+1),$difficulty,$scenario,$objective,password_hash($flag,PASSWORD_ARGON2ID),$solution,$refs,$points]);$id=(int)$db->lastInsertId();$previous=$id;foreach([1,2,3] as $h){$texts=["Mulai $title dengan menginventarisasi format dan metadata resource; jangan menebak flag.","Bandingkan artefak normal dan anomali pada tahap $h, lalu korelasikan timestamp atau offset.","Fokus pada keluaran tahap terakhir dari {$verbs[$i]}; token tidak memerlukan serangan ke jaringan luar."];$hint->execute([$id,$h,$texts[$h-1],[10,15,25][$h-1]]);} $secrets[$public]=$flag;}}
foreach($catalog as [$slug,$name,$icon]){$q=$db->prepare('INSERT INTO ctf_badges(slug,name,description,icon,criteria_json) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name),description=VALUES(description),criteria_json=VALUES(criteria_json)');$q->execute(["category-$slug","$name Master","Selesaikan seluruh arena $name",$icon,json_encode(['category'=>$slug,'solves'=>10])]);}
foreach([['first-flight','First Flight','Selesaikan flag pertama','◈',['solves'=>1]],['no-clues','No Clues','Selesaikan challenge tanpa hint','◎',['hints'=>0]],['speed-runner','Speed Runner','Selesaikan di bawah sepuluh menit','⚡',['seconds'=>600]],['pegasus-master','Pegasus Master','Selesaikan seluruh 100 challenge','♛',['solves'=>100]]] as $b){$q=$db->prepare('INSERT INTO ctf_badges(slug,name,description,icon,criteria_json) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name),description=VALUES(description),criteria_json=VALUES(criteria_json)');$q->execute([$b[0],$b[1],$b[2],$b[3],json_encode($b[4])]);}$db->commit();$path=dirname(__DIR__).'/storage/seed-flags-'.date('Ymd-His').'.json';file_put_contents($path,json_encode($secrets,JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR),LOCK_EX);chmod($path,0600);fwrite(STDOUT,"Seeded $n challenges. One-time flags saved to $path (0600); move to your secret manager, then delete it.\n");
