import { useEffect, useMemo, useState } from 'react'
import ArticleCard from '../components/articles/ArticleCard'
import Seo from '../components/Seo'
import { articles, categories } from '../data/articles'
const PAGE_SIZE=6
export default function Articles(){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('Semua'),[visible,setVisible]=useState(PAGE_SIZE)
 const filtered=useMemo(()=>articles.filter(a=>(category==='Semua'||a.category===category)&&`${a.title} ${a.summary} ${a.tags.join(' ')}`.toLocaleLowerCase('id-ID').includes(query.trim().toLocaleLowerCase('id-ID'))),[query,category])
 useEffect(()=>setVisible(PAGE_SIZE),[query,category]); const reset=()=>{setQuery('');setCategory('Semua')}
 return <section className="page articles-page" aria-labelledby="articles-title"><Seo title="Security Insight | Xech Cyber Security" description="Panduan praktis dan analisis ancaman dari tim Xech Cyber Security." path="/articles"/><header className="articles-heading"><p className="eyebrow">XECH INTELLIGENCE</p><h1 id="articles-title">Insight untuk keputusan keamanan yang lebih tajam.</h1><p>Panduan praktis, analisis ancaman, dan kerangka pertahanan yang dapat diterapkan tanpa klaim sensasional.</p></header><div className="featured-article"><span className="featured-label">PILIHAN EDITOR</span><ArticleCard article={articles[0]} featured/></div><div className="article-filters" role="search" aria-label="Pencarian dan filter artikel"><label>Cari insight<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari topik, judul, atau tag…"/></label><label>Kategori<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><p aria-live="polite"><strong>{filtered.length}</strong> artikel ditemukan</p></div>{filtered.length?<><div className="article-grid">{filtered.slice(0,visible).map(a=><ArticleCard article={a} key={a.slug}/>)}</div>{visible<filtered.length&&<div className="load-more"><button type="button" className="button secondary" onClick={()=>setVisible(v=>v+PAGE_SIZE)}>Muat lebih banyak</button></div>}</>:<div className="article-empty" role="status"><h2>Tidak ada insight yang cocok.</h2><p>Coba kata kunci yang lebih umum atau tampilkan semua kategori.</p><button type="button" className="button secondary" onClick={reset}>Atur ulang filter</button></div>}</section>
}
