import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'

const assessmentQuestions = [
  ['identity', 'MFA & akun', 'Apakah MFA diwajibkan untuk email, akun admin, dan layanan cloud?'],
  ['backup', 'Backup', 'Apakah backup penting diuji pemulihannya dan memiliki salinan terisolasi?'],
  ['patch', 'Patch', 'Apakah aset dan patch kritis dipantau dengan target waktu yang jelas?'],
  ['people', 'Phishing', 'Apakah staf menerima pelatihan dan simulasi phishing berkala?'],
  ['response', 'Respons insiden', 'Apakah organisasi memiliki playbook, kontak, dan latihan respons insiden?'],
  ['visibility', 'Monitoring', 'Apakah log keamanan dipusatkan, ditinjau, dan memiliki alert prioritas?'],
  ['vendor', 'Vendor', 'Apakah risiko dan akses pihak ketiga dievaluasi secara berkala?'],
  ['endpoint', 'Endpoint', 'Apakah endpoint dilindungi, dienkripsi, dan dapat diisolasi saat insiden?'],
  ['access', 'Akses', 'Apakah akses ditinjau berkala dan segera dicabut ketika tidak diperlukan?'],
  ['governance', 'Tata kelola', 'Apakah pemilik risiko, kebijakan, dan metrik keamanan sudah ditetapkan?'],
]
const choices = [['Belum', 0], ['Sebagian', 1], ['Sudah', 2]]
const riskServices = { identity: 'Identity & Access Review', backup: 'Resilience & Recovery Review', patch: 'Vulnerability Assessment', people: 'Security Awareness', response: 'Incident Response Readiness', visibility: 'SOC & Monitoring', vendor: 'Third-party Risk Review', endpoint: 'Endpoint Security Review', access: 'Access Control Review', governance: 'Security Governance' }

const incidents = {
  ransomware: { label: 'Ransomware', now: ['Isolasi perangkat terdampak dari jaringan tanpa mematikannya bila aman.', 'Aktifkan tim respons dan catat waktu serta sistem terdampak.', 'Amankan backup dari akses lingkungan yang terkompromi.'], avoid: ['Jangan menghapus file, menjalankan pembersih, atau bernegosiasi tanpa otorisasi.', 'Jangan menghubungkan backup ke sistem terdampak.'], evidence: ['Foto pesan tebusan, hostname, waktu, akun aktif, alert EDR, dan log jaringan.'], minimum: ['Kontak penanggung jawab, jumlah aset, waktu deteksi, dampak layanan, dan tindakan yang sudah dilakukan.'] },
  account: { label: 'Akun diretas', now: ['Gunakan perangkat tepercaya untuk reset kredensial dan cabut seluruh sesi.', 'Periksa MFA, recovery method, forwarding rule, dan perubahan hak akses.', 'Hubungi pihak terkait melalui kanal terpisah bila akun dipakai menipu.'], avoid: ['Jangan hanya mengganti password tanpa mencabut token/sesi.', 'Jangan menghapus email atau log mencurigakan.'], evidence: ['Login history, IP, user-agent, email header, perubahan rule, dan audit log.'], minimum: ['Identitas akun, layanan, waktu indikasi awal, akses admin, dan dampak.'] },
  breach: { label: 'Kebocoran data', now: ['Batasi akses ke sumber kebocoran dan libatkan fungsi legal/privacy.', 'Identifikasi jenis, pemilik, rentang waktu, dan penerima data.', 'Pertahankan log dan buat kronologi keputusan.'], avoid: ['Jangan membuat pernyataan publik sebelum fakta dan kewajiban notifikasi ditinjau.', 'Jangan menyalin data sensitif ke kanal tidak aman.'], evidence: ['Access log, konfigurasi, sampel minimal yang disanitasi, tiket, dan kronologi.'], minimum: ['Jenis data, perkiraan cakupan, lokasi sistem, yurisdiksi, dan kontak legal.'] },
  defacement: { label: 'Defacement website', now: ['Alihkan trafik ke halaman pemeliharaan bila tersedia.', 'Ambil snapshot dan isolasi deployment atau akun yang dicurigai.', 'Rotasi secret setelah bukti serta dependensi akses dipetakan.'], avoid: ['Jangan langsung menimpa server sebelum snapshot/log diamankan.'], evidence: ['Screenshot, file berubah, deployment log, WAF log, dan akun pengubah.'], minimum: ['Domain, hosting, waktu perubahan, akses panel, dan status backup.'] },
  phishing: { label: 'Phishing / BEC', now: ['Laporkan pesan, blokir pengirim/domain, dan telusuri penerima lain.', 'Jika ada transaksi, hubungi bank melalui kanal resmi secepatnya.', 'Cabut sesi serta periksa rule mailbox bila kredensial dimasukkan.'], avoid: ['Jangan meneruskan lampiran berbahaya sebagai attachment biasa.', 'Jangan membalas pelaku.'], evidence: ['Email asli sebagai .eml, header lengkap, URL, rekening, dan waktu interaksi.'], minimum: ['Jumlah penerima, tindakan pengguna, transaksi, akun, dan perangkat.'] },
  malware: { label: 'Malware perangkat', now: ['Isolasi perangkat melalui EDR atau jaringan.', 'Catat proses, alert, pengguna, dan koneksi sebelum perubahan.', 'Cari indikator serupa pada aset lain.'], avoid: ['Jangan mematikan atau melakukan factory reset sebelum triase bila aman.'], evidence: ['Alert EDR, process tree, hash, koneksi, memory/disk image sesuai prosedur.'], minimum: ['Hostname, pengguna, OS, waktu, alert, dan konektivitas.'] },
  ddos: { label: 'Serangan DDoS', now: ['Hubungi penyedia hosting/ISP dan aktifkan proteksi DDoS.', 'Terapkan rate limiting atau traffic filtering yang telah diuji.', 'Pantau kapasitas, origin, dan layanan dependensi.'], avoid: ['Jangan memblokir rentang luas tanpa menilai dampak pengguna sah.'], evidence: ['Grafik trafik, NetFlow/WAF/CDN log, target endpoint, dan waktu.'], minimum: ['Domain/IP, provider, baseline dan puncak trafik, dampak, serta durasi.'] },
}

const paths = [
  ['pemula', 'Keamanan Siber untuk Pemula', 45, ['Kenali aset dan risiko', 'Password manager & MFA', 'Phishing dasar']],
  ['umkm', 'Panduan untuk UMKM', 55, ['Prioritas kontrol dasar', 'Backup yang dapat dipulihkan', 'Rencana insiden ringkas']],
  ['it', 'Panduan untuk Tim IT', 80, ['Inventaris & hardening', 'Patch berbasis risiko', 'Logging dan triase']],
  ['management', 'Panduan untuk Manajemen', 40, ['Akuntabilitas risiko', 'Metrik yang berguna', 'Latihan krisis']],
  ['ir', 'Persiapan Incident Response', 65, ['Peran dan kontak', 'Playbook & bukti', 'Tabletop exercise']],
  ['cloud', 'Dasar Cloud Security', 70, ['Shared responsibility', 'Identity & secret', 'Logging cloud']],
  ['phishing', 'Phishing Awareness', 35, ['Tanda bahaya', 'Verifikasi kanal lain', 'Lapor dengan aman']],
]
const advisories = [
  { vendor: 'CISA', severity: 'Kritis', category: 'Critical vulnerabilities', title: 'Known Exploited Vulnerabilities Catalog', action: 'Cocokkan katalog dengan inventaris dan ikuti tenggat remediasi vendor.', checked: '26 Agustus 2026', url: 'https://www.cisa.gov/known-exploited-vulnerabilities-catalog' },
  { vendor: 'NIST', severity: 'Referensi', category: 'Web application', title: 'National Vulnerability Database', action: 'Verifikasi detail CVE dan tautan vendor sebelum mengambil keputusan.', checked: '26 Agustus 2026', url: 'https://nvd.nist.gov/' },
  { vendor: 'Microsoft', severity: 'Vendor', category: 'Endpoint', title: 'Security Response Center', action: 'Tinjau panduan dan pembaruan langsung dari vendor.', checked: '26 Agustus 2026', url: 'https://msrc.microsoft.com/update-guide' },
  { vendor: 'Cisco', severity: 'Vendor', category: 'Network appliances', title: 'Cisco Security Advisories', action: 'Periksa produk/versi yang terdampak dan mitigasi resmi.', checked: '26 Agustus 2026', url: 'https://sec.cloudapps.cisco.com/security/center/publicationListing.x' },
]
const glossary = { MFA: 'Verifikasi identitas dengan dua atau lebih faktor berbeda.', 'Zero Trust': 'Pendekatan yang terus memverifikasi akses berdasarkan identitas, perangkat, dan konteks.', SIEM: 'Platform untuk mengumpulkan serta menganalisis event dan log keamanan.', EDR: 'Kemampuan deteksi dan respons pada endpoint.', CVE: 'Pengenal publik untuk kerentanan keamanan yang diketahui.', CVSS: 'Metode standar untuk memberi skor karakteristik teknis kerentanan.', Phishing: 'Manipulasi melalui pesan atau situs palsu untuk mencuri data atau memicu tindakan.', Ransomware: 'Malware yang mengganggu akses data/sistem dan sering disertai pemerasan.', DLP: 'Kontrol untuk mengidentifikasi dan mengurangi kebocoran data sensitif.' }

function useStoredProgress() {
  const [value, setValue] = useState(() => { try { const raw = JSON.parse(localStorage.getItem('xech_learning_v1')); return raw?.version === 1 && raw.items && typeof raw.items === 'object' ? raw.items : {} } catch { return {} } })
  useEffect(() => { try { localStorage.setItem('xech_learning_v1', JSON.stringify({ version: 1, items: value })) } catch { /* Penyimpanan opsional. */ } }, [value])
  return [value, setValue]
}

export default function CyberTools() {
  const [answers, setAnswers] = useState({}), [assessmentDone, setAssessmentDone] = useState(false)
  const [incidentKey, setIncidentKey] = useState('ransomware')
  const [scope, setScope] = useState({ size: '11–50', endpoints: '26–100', apps: '2–5', industry: 'Umum', compliance: 'Belum ditentukan', testing: 'Vulnerability Assessment', urgency: 'Normal', timeline: '1–3 bulan' })
  const [progress, setProgress] = useStoredProgress()
  const [advisoryFilter, setAdvisoryFilter] = useState('Semua')
  const [policy, setPolicy] = useState({ profile: 'UMKM', name: 'Organisasi Anda', selected: ['Password dan MFA', 'Pelaporan Insiden'] })
  const [simStep, setSimStep] = useState(0), [simScore, setSimScore] = useState(0), [simNotes, setSimNotes] = useState([])
  const [subscription, setSubscription] = useState(''), [subStatus, setSubStatus] = useState('')
  const [caseFilter, setCaseFilter] = useState('Semua'), [term, setTerm] = useState('')
  const [reading, setReading] = useState(() => { try { const raw = JSON.parse(localStorage.getItem('xech_reading_v1')); return raw?.version === 1 ? raw : { version: 1, bookmarks: [], completed: [], recent: [] } } catch { return { version: 1, bookmarks: [], completed: [], recent: [] } } })
  useEffect(() => { try { localStorage.setItem('xech_reading_v1', JSON.stringify(reading)) } catch { /* Penyimpanan opsional. */ } }, [reading])
  const answered = Object.keys(answers).length
  const score = Object.values(answers).reduce((a, b) => a + b, 0)
  const maturity = score < 8 ? 'Dasar' : score < 15 ? 'Berkembang' : 'Matang'
  const risks = assessmentQuestions.filter(([id]) => (answers[id] ?? 0) < 2).sort(([a], [b]) => (answers[a] ?? 0) - (answers[b] ?? 0)).slice(0, 3)
  const estimate = useMemo(() => {
    const large = scope.size.includes('200') || scope.endpoints.includes('500') || scope.apps.includes('10+')
    return { package: large ? 'Enterprise Assurance' : scope.testing.includes('Penetration') ? 'Focused Offensive Review' : 'Essential Security Baseline', duration: large ? '4–8 minggu' : scope.urgency === 'Mendesak' ? '1–2 minggu setelah scope disepakati' : '2–4 minggu', activities: scope.testing.includes('Penetration') ? ['Kickoff & rules of engagement', 'Pengujian terkontrol', 'Validasi temuan', 'Laporan dan debrief'] : ['Inventaris dan discovery', 'Pemindaian terautentikasi bila disetujui', 'Validasi risiko', 'Roadmap remediasi'], prep: ['Kontak teknis dan bisnis', 'Daftar aset serta owner', 'Jendela pengujian', 'Persetujuan tertulis dan batas scope'] }
  }, [scope])
  const policyText = `# Template Kebijakan Keamanan — ${policy.name}\n\nProfil: ${policy.profile}\nStatus: Draf edukatif — wajib ditinjau pemilik kebijakan dan penasihat yang relevan.\n\n${policy.selected.map((x, i) => `## ${i + 1}. ${x}\n${policy.name} menetapkan pemilik kontrol, ruang lingkup, pengecualian terdokumentasi, jadwal tinjauan, serta mekanisme pelaporan untuk ${x.toLowerCase()}. Bukti penerapan ditinjau secara berkala.`).join('\n\n')}\n\n## Persetujuan dan tinjauan\nPemilik: [isi]\nDisetujui: [isi]\nTinjauan berikutnya: [isi]\n`
  const downloadPolicy = () => { const blob = new Blob([policyText], { type: 'text/markdown' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = 'template-kebijakan-keamanan.md'; a.click(); URL.revokeObjectURL(a.href) }
  const simulation = [
    { text: 'Seorang staf membuka lampiran dan perangkat mulai mengenkripsi file. Apa langkah pertama?', options: [['Isolasi perangkat dan aktifkan jalur respons', 3, 'Membatasi penyebaran sambil menjaga peluang pengumpulan bukti.'], ['Matikan semua server tanpa koordinasi', 0, 'Dapat memperbesar gangguan dan menghilangkan konteks penting.'], ['Tunggu untuk memastikan', 0, 'Penundaan dapat memperluas dampak.']] },
    { text: 'Tim menemukan backup yang belum terhubung. Apa keputusan berikutnya?', options: [['Jaga tetap terisolasi dan verifikasi salinan melalui lingkungan bersih', 3, 'Melindungi jalur pemulihan dari kompromi.'], ['Sambungkan ke jaringan produksi untuk mengecek file', 0, 'Berisiko membuat backup ikut terdampak.'], ['Hapus alert agar dashboard bersih', 0, 'Menghilangkan informasi penting untuk triase.']] },
    { text: 'Pimpinan meminta komunikasi publik segera. Apa respons terbaik?', options: [['Susun fakta terverifikasi bersama legal, privacy, dan komunikasi', 3, 'Komunikasi akurat perlu koordinasi dan memperhatikan kewajiban notifikasi.'], ['Bagikan dugaan penyebab di media sosial', 0, 'Spekulasi dapat menyesatkan dan mengganggu investigasi.'], ['Jangan dokumentasikan apa pun', 0, 'Kronologi keputusan penting untuk koordinasi dan evaluasi.']] },
  ]
  const simChoose = (points, note) => { setSimScore(v => v + points); setSimNotes(v => [...v, note]); setSimStep(v => v + 1) }
  const cases = [
    ['UMKM', 'Vulnerability Assessment', 'Contoh anonim: membangun baseline aset', 'Inventaris tersebar menyulitkan prioritas.', 'Discovery, validasi aman, dan roadmap berbasis risiko.', 'Outcome demonstrasi; tidak mewakili hasil klien nyata.'],
    ['Teknologi', 'Penetration Testing', 'Contoh anonim: menguji aplikasi sebelum rilis', 'Tim membutuhkan validasi independen sebelum go-live.', 'Rules of engagement, pengujian terkontrol, retest.', 'Outcome demonstrasi; metrik sengaja tidak diklaim.'],
    ['Jasa', 'Incident Readiness', 'Contoh anonim: latihan koordinasi insiden', 'Kontak dan keputusan eskalasi belum teruji.', 'Workshop playbook dan tabletop lintas fungsi.', 'Outcome demonstrasi; identitas organisasi tidak ditampilkan.'],
  ]
  return <div className="tools-page">
    <section className="tools-hero"><p className="eyebrow">CYBER READINESS CENTER</p><h1>Alat praktis untuk <span>keputusan keamanan</span> yang lebih baik.</h1><p>Asesmen, panduan insiden, learning path, dan template edukatif—tanpa akun dan tanpa menyimpan identitas. Pilih alat sesuai kebutuhan Anda.</p><nav className="tools-jump" aria-label="Navigasi alat">{[['assessment','Asesmen'],['incident','Respons Insiden'],['estimator','Estimator'],['learning','Learning Path'],['advisory','Advisory'],['more','Alat Lain']].map(x=><a href={`#${x[0]}`} key={x[0]}>{x[1]}</a>)}</nav></section>

    <section id="assessment" className="tool-section"><div className="tool-heading"><span>01</span><div><p className="eyebrow">SELF-ASSESSMENT</p><h2>Ukur kesiapan awal organisasi</h2><p>Jawab 10 pertanyaan. Hasil ini adalah indikasi edukatif, bukan audit, sertifikasi, atau jaminan keamanan.</p></div></div>
      <div className="assessment-progress"><progress max="10" value={answered}/><span>{answered}/10 dijawab</span></div>
      <div className="question-grid">{assessmentQuestions.map(([id,label,q], i)=><fieldset className="tool-card" key={id}><legend><span>{String(i+1).padStart(2,'0')}</span>{label}</legend><p>{q}</p><div className="choice-row">{choices.map(([name,value])=><button className={answers[id]===value?'selected':''} type="button" onClick={()=>{setAnswers(v=>({...v,[id]:value}));setAssessmentDone(false)}} key={name}>{name}</button>)}</div></fieldset>)}</div>
      <button className="button" disabled={answered < 10} onClick={()=>setAssessmentDone(true)}>Lihat hasil asesmen</button>
      {assessmentDone&&<div className="result-panel" aria-live="polite"><div className="score-ring"><strong>{score}</strong><span>/ 20</span></div><div><p className="eyebrow">TINGKAT KESIAPAN</p><h3>{maturity}</h3><p>{maturity==='Dasar'?'Prioritaskan kontrol dasar dan tetapkan pemilik tindakan.':maturity==='Berkembang'?'Fondasi tersedia; konsistensi, pengujian, dan bukti penerapan perlu diperkuat.':'Kontrol dasar tampak matang; lanjutkan validasi independen dan perbaikan berkelanjutan.'}</p><h4>3 risiko utama & layanan relevan</h4><ul>{risks.map(([id,label])=><li key={id}><strong>{label}:</strong> {riskServices[id]}</li>)}</ul><h4>Checklist 30 hari</h4><ol><li>Tetapkan pemilik dan tenggat untuk tiga risiko teratas.</li><li>Validasi bukti penerapan, bukan hanya dokumen kebijakan.</li><li>Uji satu skenario pemulihan atau respons insiden.</li><li>Tinjau hasil bersama pimpinan dan susun roadmap 90 hari.</li></ol><div className="actions"><Link className="button" to="/contact">Diskusikan hasil secara rahasia</Link><button className="button secondary" onClick={()=>navigator.clipboard?.writeText(`Checklist 30 hari (${maturity}):\n1. Tetapkan pemilik tiga risiko teratas.\n2. Validasi bukti penerapan.\n3. Uji pemulihan/respons.\n4. Susun roadmap 90 hari.`)}>Salin checklist</button><button className="button secondary" onClick={()=>window.print()}>Cetak / PDF</button></div></div></div>}
    </section>

    <section id="incident" className="tool-section"><div className="tool-heading"><span>02</span><div><p className="eyebrow">QUICK GUIDE</p><h2>Sedang mengalami insiden?</h2><p>Gunakan langkah awal ini sambil mengaktifkan prosedur organisasi. Jangan mengirim bukti sensitif melalui kanal yang belum diverifikasi.</p></div></div><div className="incident-layout"><div className="incident-tabs" role="tablist">{Object.entries(incidents).map(([key,item])=><button role="tab" aria-selected={incidentKey===key} onClick={()=>setIncidentKey(key)} key={key}>{item.label}</button>)}</div><article className="incident-guide"><h3>{incidents[incidentKey].label}</h3>{[['Tindakan segera','now'],['Jangan dilakukan','avoid'],['Bukti yang dipertahankan','evidence'],['Data minimum saat meminta bantuan','minimum']].map(([title,key])=><div key={key}><h4>{title}</h4><ul>{incidents[incidentKey][key].map(x=><li key={x}>{x}</li>)}</ul></div>)}<div className="warning-box"><strong>Kanal eskalasi belum dipublikasikan.</strong><p>Gunakan kontak insiden resmi organisasi yang telah diverifikasi. Form situs bukan kanal untuk bukti rahasia atau material berbahaya.</p><Link className="button secondary" to="/contact">Lihat kanal konsultasi</Link></div></article></div></section>

    <section id="estimator" className="tool-section"><div className="tool-heading"><span>03</span><div><p className="eyebrow">SCOPE ESTIMATOR</p><h2>Rancang ruang lingkup awal</h2><p>Estimasi ini bukan penawaran harga atau jadwal final. Scope harus dikonfirmasi melalui rules of engagement.</p></div></div><div className="estimator-layout"><div className="scope-form">{[['size','Ukuran organisasi',['1–10','11–50','51–200','200+']],['endpoints','Jumlah endpoint',['1–25','26–100','101–500','500+']],['apps','Aplikasi/domain',['1','2–5','6–10','10+']],['industry','Industri',['Umum','Keuangan','Kesehatan','Teknologi','Pemerintahan']],['compliance','Kebutuhan compliance',['Belum ditentukan','ISO 27001','PCI DSS','Regulasi internal/lainnya']],['testing','Jenis pengujian',['Vulnerability Assessment','Penetration Testing','Cloud Security Review','Incident Readiness']],['urgency','Urgensi',['Normal','Prioritas','Mendesak']],['timeline','Target waktu',['< 1 bulan','1–3 bulan','3–6 bulan']]].map(([key,label,opts])=><label key={key}>{label}<select value={scope[key]} onChange={e=>setScope(v=>({...v,[key]:e.target.value}))}>{opts.map(x=><option key={x}>{x}</option>)}</select></label>)}</div><aside className="scope-result"><p className="eyebrow">ESTIMASI RUANG LINGKUP</p><h3>{estimate.package}</h3><p><strong>Perkiraan durasi:</strong> {estimate.duration}</p><h4>Aktivitas</h4><ul>{estimate.activities.map(x=><li key={x}>{x}</li>)}</ul><h4>Yang perlu disiapkan</h4><ul>{estimate.prep.map(x=><li key={x}>{x}</li>)}</ul><Link className="button" to="/contact">Diskusikan scope</Link></aside></div></section>

    <section id="disclosure" className="tool-section split-section"><div><p className="eyebrow">RESPONSIBLE DISCLOSURE</p><h2>Portal laporan kerentanan</h2><p className="warning-box"><strong>Draf kebijakan—belum menjadi otorisasi pengujian.</strong> Scope, safe harbor, SLA, kanal terenkripsi, dan PGP key wajib disetujui tim operasional serta legal sebelum portal menerima laporan.</p><h3>Sistem yang boleh diuji</h3><p>Belum ada aset yang dinyatakan in-scope. Tanpa izin tertulis, jangan melakukan pengujian.</p><h3>Di luar scope</h3><ul><li>Social engineering, DDoS, spam, dan pengujian fisik.</li><li>Akses, perubahan, pengunduhan, atau penghapusan data pengguna.</li><li>Sistem pihak ketiga dan tindakan yang mengganggu layanan.</li></ul></div><div className="tool-card"><h3>Format laporan yang disiapkan</h3><ol><li>Aset dan URL/komponen terdampak.</li><li>Ringkasan dampak tanpa mengekspos data.</li><li>Langkah reproduksi minimal dan aman.</li><li>Waktu pengujian, IP sumber opsional, serta environment.</li><li>Saran remediasi dan preferensi koordinasi publikasi.</li></ol><h3>Target acknowledgment</h3><p>Akan ditetapkan setelah kapasitas triase dan on-call disetujui. Jangan mencantumkan SLA yang belum dapat dipenuhi.</p><h3>Kanal aman</h3><p>PGP key dan alamat laporan belum tersedia. Jangan kirim temuan sensitif melalui form umum.</p></div></section>

    <section id="learning" className="tool-section"><div className="tool-heading"><span>05</span><div><p className="eyebrow">KNOWLEDGE HUB</p><h2>Learning path sesuai peran</h2><p>Progress tersimpan lokal di browser, tanpa akun. Centang materi yang sudah selesai.</p></div></div><div className="path-grid">{paths.map(([id,title,minutes,steps])=>{const done=steps.filter((_,i)=>progress[`${id}-${i}`]).length;return <article className="tool-card" key={id}><p className="eyebrow">{minutes} MENIT · {done}/{steps.length}</p><h3>{title}</h3><progress max={steps.length} value={done}/>{steps.map((step,i)=><label className="check-row" key={step}><input type="checkbox" checked={!!progress[`${id}-${i}`]} onChange={e=>setProgress(v=>({...v,[`${id}-${i}`]:e.target.checked}))}/><span>{step}</span></label>)}<div className="card-actions"><Link to="/information">Buka panduan</Link><Link to="/quiz">Kuis penutup</Link></div></article>})}</div><button className="text-button" onClick={()=>setProgress({})}>Reset seluruh progress lokal</button></section>

    <section id="advisory" className="tool-section"><div className="tool-heading"><span>06</span><div><p className="eyebrow">ADVISORY WATCHLIST</p><h2>Sumber advisori primer</h2><p>Dashboard ini mengarahkan ke katalog resmi; bukan feed real-time. Verifikasi produk, versi, eksploitasi, dan mitigasi langsung pada sumber.</p></div></div><label className="inline-filter">Filter kategori<select value={advisoryFilter} onChange={e=>setAdvisoryFilter(e.target.value)}><option>Semua</option>{[...new Set(advisories.map(x=>x.category))].map(x=><option key={x}>{x}</option>)}</select></label><div className="advisory-list">{advisories.filter(x=>advisoryFilter==='Semua'||x.category===advisoryFilter).map(x=><article className="tool-card" key={x.title}><div className="badge-row"><span>{x.severity}</span><span>{x.category}</span></div><h3>{x.title}</h3><p>{x.action}</p><small>Terakhir diverifikasi: {x.checked}</small><a href={x.url} target="_blank" rel="noreferrer">Buka sumber resmi ↗</a></article>)}</div></section>

    <section id="more" className="tool-section"><div className="tool-heading"><span>07–14</span><div><p className="eyebrow">MORE TOOLS</p><h2>Template, simulasi, dan sumber belajar</h2></div></div>
      <div className="feature-stack"><article className="feature-panel"><div><p className="eyebrow">POLICY GENERATOR</p><h3>Generator kebijakan keamanan dasar</h3><p>Template edukatif ini bukan nasihat hukum, bukti compliance, atau pengganti review internal.</p><label>Nama organisasi<input value={policy.name} onChange={e=>setPolicy(v=>({...v,name:e.target.value}))}/></label><label>Profil<select value={policy.profile} onChange={e=>setPolicy(v=>({...v,profile:e.target.value}))}><option>UMKM</option><option>Startup teknologi</option><option>Organisasi menengah</option></select></label>{['Acceptable Use','Password dan MFA','Pelaporan Insiden','Backup','Remote Work','Access Control','Vendor Security Checklist'].map(x=><label className="check-row" key={x}><input type="checkbox" checked={policy.selected.includes(x)} onChange={e=>setPolicy(v=>({...v,selected:e.target.checked?[...v.selected,x]:v.selected.filter(y=>y!==x)}))}/>{x}</label>)}<div className="actions"><button className="button" onClick={downloadPolicy}>Unduh Markdown</button><button className="button secondary" onClick={()=>window.print()}>Cetak / simpan PDF</button></div></div><pre className="policy-preview">{policyText}</pre></article>
      <article className="feature-panel"><div><p className="eyebrow">TABLETOP SIMULATION</p><h3>Simulasi respons ransomware</h3>{simStep<simulation.length?<><p className="scenario-count">Skenario {simStep+1}/{simulation.length}</p><h4>{simulation[simStep].text}</h4><div className="simulation-options">{simulation[simStep].options.map(([label,points,note])=><button key={label} onClick={()=>simChoose(points,note)}>{label}</button>)}</div></>:<div className="result-panel"><div><h3>Skor keputusan: {simScore}/9</h3><p>{simScore===9?'Keputusan menjaga containment, recovery, bukti, dan komunikasi.':'Tinjau kembali playbook dan latihan koordinasi lintas fungsi.'}</p><ul>{simNotes.map((x,i)=><li key={i}>{x}</li>)}</ul><button className="button secondary" onClick={()=>{setSimStep(0);setSimScore(0);setSimNotes([])}}>Ulangi simulasi</button> <Link className="button" to="/contact">Diskusikan tabletop profesional</Link></div></div>}</div></article>
      <article className="feature-panel"><div><p className="eyebrow">ALERT SUBSCRIPTION</p><h3>Newsletter & alert</h3><p>Demo preferensi. Belum terhubung ke provider email dan tidak mengirim atau menyimpan alamat.</p><form className="mini-form" onSubmit={e=>{e.preventDefault();setSubStatus('Preferensi tervalidasi. Integrasi double opt-in belum diaktifkan; tidak ada data yang dikirim.')}}><label>Email<input required type="email" value={subscription} onChange={e=>setSubscription(e.target.value)}/></label>{['Weekly security digest','Critical vulnerability alert','Panduan UMKM','Event dan webinar','Artikel baru'].map(x=><label className="check-row" key={x}><input type="checkbox"/>{x}</label>)}<label className="check-row"><input required type="checkbox"/>Saya memahami privacy notice, double opt-in, hak unsubscribe, dan kebijakan retensi harus tersedia sebelum aktivasi.</label><label aria-hidden="true" className="honeypot">Jangan isi<input tabIndex="-1" autoComplete="off"/></label><button className="button">Validasi preferensi</button><p role="status" className="status">{subStatus}</p></form></div></article>
      <article className="feature-panel"><div><p className="eyebrow">CASE STUDY LIBRARY</p><h3>Studi kasus aman dan terstruktur</h3><label>Filter industri<select value={caseFilter} onChange={e=>setCaseFilter(e.target.value)}><option>Semua</option>{[...new Set(cases.map(x=>x[0]))].map(x=><option key={x}>{x}</option>)}</select></label><div className="case-grid">{cases.filter(x=>caseFilter==='Semua'||x[0]===caseFilter).map(x=><section className="tool-card" key={x[2]}><span className="badge">{x[0]} · {x[1]}</span><h4>{x[2]}</h4><p><strong>Masalah:</strong> {x[3]}</p><p><strong>Pendekatan:</strong> {x[4]}</p><small>{x[5]}</small></section>)}</div></div></article>
      <article className="feature-panel"><div><p className="eyebrow">READING & PRINT</p><h3>Bookmark, riwayat, dan ekspor</h3><p>Bookmark, status selesai, dan lima bacaan terakhir disimpan lokal dengan schema berversi. Tidak ada akun atau identitas yang dikirim.</p><div className="reading-list">{[['article-security','Artikel keamanan defensif','/articles'],['guide-security','Panduan informasi keamanan','/information'],['path-ir','Learning path incident response','#learning']].map(([id,title,to])=>{const bookmarked=reading.bookmarks.includes(id),completed=reading.completed.includes(id);return <div className="tool-card" key={id}><Link to={to} onClick={()=>setReading(v=>({...v,recent:[id,...v.recent.filter(x=>x!==id)].slice(0,5)}))}>{title}</Link><div className="card-actions"><button onClick={()=>setReading(v=>({...v,bookmarks:bookmarked?v.bookmarks.filter(x=>x!==id):[...v.bookmarks,id]}))}>{bookmarked?'Hapus bookmark':'Simpan bookmark'}</button><button onClick={()=>setReading(v=>({...v,completed:completed?v.completed.filter(x=>x!==id):[...v.completed,id]}))}>{completed?'Tandai belum selesai':'Tandai selesai'}</button></div></div>})}</div><p><strong>Riwayat terakhir:</strong> {reading.recent.length?reading.recent.join(' · '):'Belum ada bacaan dibuka.'}</p><div className="actions"><button className="button secondary" onClick={()=>window.print()}>Cetak halaman / PDF</button><button className="button secondary" onClick={()=>setReading({version:1,bookmarks:[],completed:[],recent:[]})}>Reset data membaca</button></div><p className="qr-placeholder"><strong>Tautan cepat</strong><br/><code>{window.location.origin}/cyber-tools</code><br/><button className="text-button" onClick={()=>navigator.clipboard?.writeText(`${window.location.origin}/cyber-tools`)}>Salin tautan untuk QR</button><br/><small>Tempel tautan ke generator QR yang disetujui organisasi. Situs tidak mengirim URL ke layanan pihak ketiga.</small></p></div></article>
      <article className="feature-panel"><div><p className="eyebrow">GLOSSARY</p><h3>Glosarium keamanan siber</h3><label>Cari istilah<input value={term} onChange={e=>setTerm(e.target.value)} placeholder="Contoh: MFA"/></label><dl className="glossary">{Object.entries(glossary).filter(([k,v])=>(k+' '+v).toLowerCase().includes(term.toLowerCase())).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></div></article>
      <article className="feature-panel"><div><p className="eyebrow">EVENT CALENDAR</p><h3>Webinar & workshop</h3><p>Belum ada jadwal publik yang telah diverifikasi. Kalender berikut menampilkan format program, bukan tanggal acara nyata.</p><div className="event-grid">{[['Webinar','Security Baseline untuk UMKM','Jadwal akan diumumkan'],['Workshop','Menyusun playbook incident response','Jadwal akan diumumkan'],['Rekaman','Dasar phishing awareness','Materi menunggu persetujuan publikasi']].map(x=><div className="tool-card" key={x[1]}><span className="badge">{x[0]}</span><h4>{x[1]}</h4><p>{x[2]}</p><button disabled className="button secondary">Registrasi belum dibuka</button></div>)}</div><p>Integrasi kalender akan tersedia setelah tanggal, zona waktu, narasumber, privacy notice, dan kapasitas acara dikonfirmasi.</p></div></article></div>
    </section>
  </div>
}
