import {useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {demoChallenges} from './catalog';
import {Difficulty,Progress,State} from '../../components/pegasus/Ui';
import {getChallenge,startChallenge,submitFlag,unlockHint} from '../../services/pegasusApi';

export default function ChallengeDetail(){
  const {id}=useParams(),[challenge,setChallenge]=useState(null),[loading,setLoading]=useState(true),[demo,setDemo]=useState(false),[seconds,setSeconds]=useState(0),[flag,setFlag]=useState(''),[hints,setHints]=useState([]),[toast,setToast]=useState(''),[solved,setSolved]=useState(false),[attempts,setAttempts]=useState(0),[busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;const fallback=demoChallenges.find(x=>String(x.id)===id);setLoading(true);getChallenge(id).then(async data=>{if(!active)return;setChallenge(data);setAttempts(Number(data.attempts)||0);setSolved(data.status==='completed');if(data.status==='not_started')await startChallenge(id)}).catch(()=>{if(active){setChallenge(fallback||null);setDemo(Boolean(fallback))}}).finally(()=>active&&setLoading(false));return()=>{active=false}},[id]);
  useEffect(()=>{if(!challenge||solved)return;const t=setInterval(()=>setSeconds(x=>x+1),1000);return()=>clearInterval(t)},[challenge,solved]);
  if(loading)return <section className="peg-workspace"><State/></section>;
  if(!challenge)return <section className="peg-workspace"><State type="error" message="Challenge tidak ditemukan."/><div className="peg-actions"><Link className="peg-button ghost" to="/pegasus/challenges">Kembali ke direktori</Link></div></section>;
  const maxAttempts=Number(challenge.max_attempts)||20,timeLimit=Number(challenge.time_limit_minutes)||60,used=Math.max(Number(challenge.hints_used)||0,hints.length),penalty=[0,10,25,50][used],potential=Math.round(Number(challenge.base_points||challenge.points)*(1-penalty/100));
  const send=async e=>{e.preventDefault();if(!/^PEGASUS\{[a-zA-Z0-9_:-]{3,140}\}$/.test(flag)){setToast('Format flag tidak valid.');return}setBusy(true);try{const result=await submitFlag(id,flag);setAttempts(x=>x+1);setSolved(result.correct);setToast(result.correct?`Flag benar! +${result.points_awarded} poin`:'Flag salah. Percobaan dicatat.');if(result.correct)setFlag('')}catch(error){setToast(demo?'Mode pratinjau tidak dapat memvalidasi flag. Hubungkan API dan masuk sebagai operator.':error.message)}finally{setBusy(false)}};
  const hint=async order=>{setBusy(true);try{const result=await unlockHint(id,order);setHints(value=>[...value,result.content])}catch(error){setToast(demo?'Hint terkunci di mode pratinjau. Hubungkan API untuk membukanya.':error.message)}finally{setBusy(false)}};
  return <section className="peg-workspace"><header><div><Link to="/pegasus/challenges">← Semua Challenge</Link><h1>{challenge.title}</h1><span>{challenge.category}</span> <Difficulty value={challenge.difficulty}/></div><div className="peg-timer">SESSION {String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')} / {timeLimit}:00</div></header>{demo&&<div className="peg-notice"><strong>Mode pratinjau</strong><span>Workspace bersifat visual; submission dan hint memerlukan API terautentikasi.</span></div>}{toast&&<div className={`peg-toast ${solved?'success':''}`} role="alert">{toast}<button type="button" aria-label="Tutup notifikasi" onClick={()=>setToast('')}>×</button></div>}<div className="peg-workgrid"><aside className="peg-panel"><span className="peg-label">SKENARIO</span><p>{challenge.scenario||challenge.description}</p><h3>Tujuan pembelajaran</h3><p>{challenge.learning_objective||challenge.objective}</p><h3>Resource</h3><button type="button" className="peg-resource" disabled={demo}>⇩ evidence-{challenge.id}.zip <small>SHA-256 verified</small></button><h3>Aturan arena</h3><ul><li>Hanya gunakan aset sandbox.</li><li>Dilarang memindai target eksternal.</li><li>Environment berakhir dalam {timeLimit} menit.</li></ul></aside><main className="peg-terminal large"><header><span>analysis-console</span><button type="button" disabled={demo}>Reset Environment</button></header><p><b>$</b> pegasus mission start {challenge.id}</p><p className="ok">[+] Isolated workspace ready.</p><p>[i] Resource mounted read-only at /mission/evidence</p><p><b>$</b> <span className="peg-cursor">_</span></p></main><aside className="peg-panel"><div className="peg-points"><div><small>POTENSI POIN</small><strong>{potential}</strong></div><Difficulty value={challenge.difficulty}/></div><Progress label="Percobaan" value={attempts/maxAttempts*100} valueLabel={`${attempts} / ${maxAttempts}`}/><h3>Hint bertahap</h3>{[1,2,3].map(order=><button type="button" key={order} className="peg-hint" disabled={busy||solved||used<order-1} onClick={()=>hint(order)}>{hints[order-1]||`${order<=Number(challenge.hints_used||0)?'Hint telah dibuka':`Buka Hint ${order}`} (−${[10,15,25][order-1]}%)`}</button>)}<form onSubmit={send} className="peg-flag"><label htmlFor="flag">Kirim Flag</label><input id="flag" value={flag} onChange={e=>setFlag(e.target.value)} placeholder="PEGASUS{...}" autoComplete="off" spellCheck="false" disabled={busy||solved||attempts>=maxAttempts}/><button className="peg-button" disabled={busy||solved||attempts>=maxAttempts}>{busy?'Memproses…':solved?'Flag Terverifikasi':'Kirim Flag'}</button></form>{solved&&<div className="peg-solution"><h3>✓ Pembahasan terbuka</h3><p>{challenge.solution||'Muat ulang challenge untuk mengambil pembahasan terverifikasi dari backend.'}</p>{Number(id)<100&&<Link to={`/pegasus/challenges/${Number(id)+1}`}>Challenge Berikutnya →</Link>}</div>}</aside></div></section>
}
