import {useEffect,useMemo,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {categories,demoChallenges} from './catalog';
import {Difficulty,Progress,State} from '../../components/pegasus/Ui';
import {getChallenges} from '../../services/pegasusApi';

export default function ChallengeList(){
  const [params,setParams]=useSearchParams(),[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[demo,setDemo]=useState(false);
  const query=params.get('q')||'',category=params.get('category')||'',difficulty=params.get('difficulty')||'',status=params.get('status')||'',sort=params.get('sort')||'progress',view=params.get('view')||'grid';
  const update=(key,value)=>setParams(current=>{const next=new URLSearchParams(current);value?next.set(key,value):next.delete(key);return next},{replace:true});
  useEffect(()=>{let active=true;setLoading(true);getChallenges().then(data=>{if(active){setRows(data);setDemo(false)}}).catch(()=>{if(active){setRows(demoChallenges);setDemo(true)}}).finally(()=>active&&setLoading(false));return()=>{active=false}},[]);
  const filtered=useMemo(()=>rows.filter(x=>(!query||x.title.toLowerCase().includes(query.toLowerCase()))&&(!category||x.category_slug===category)&&(!difficulty||x.difficulty===difficulty)&&(!status||x.status===status)).sort((a,b)=>sort==='points'?Number(b.points)-Number(a.points):sort==='difficulty'?Number(a.points)-Number(b.points):Number(a.locked)-Number(b.locked)),[rows,query,category,difficulty,status,sort]);
  return <section className="peg-wrap peg-page"><div className="peg-heading"><div><p className="peg-kicker">MISSION DIRECTORY</p><h1>Challenge</h1></div><div className="peg-view" aria-label="Mode tampilan"><button type="button" title="Tampilan grid" onClick={()=>update('view','grid')} aria-pressed={view==='grid'}>▦</button><button type="button" title="Tampilan daftar" onClick={()=>update('view','list')} aria-pressed={view==='list'}>☷</button></div></div>{demo&&<div className="peg-notice" role="status"><strong>Mode pratinjau</strong><span>API belum terhubung. Katalog aman ditampilkan tanpa flag atau solusi.</span></div>}<div className="peg-panel peg-filters"><label>Cari<input value={query} onChange={e=>update('q',e.target.value)} placeholder="Cari judul…"/></label><label>Kategori<select value={category} onChange={e=>update('category',e.target.value)}><option value="">Semua kategori</option>{categories.map(x=><option value={x[0]} key={x[0]}>{x[1]}</option>)}</select></label><label>Kesulitan<select value={difficulty} onChange={e=>update('difficulty',e.target.value)}><option value="">Semua level</option>{['easy','medium','hard','expert'].map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={status} onChange={e=>update('status',e.target.value)}><option value="">Semua status</option><option value="not_started">Belum dimulai</option><option value="in_progress">Dikerjakan</option><option value="completed">Selesai</option></select></label><label>Urutkan<select value={sort} onChange={e=>update('sort',e.target.value)}><option value="progress">Progres</option><option value="points">Poin</option><option value="difficulty">Kesulitan</option></select></label></div>{loading?<State/>:<><Progress label="Misi ditemukan" value={filtered.length} valueLabel={`${filtered.length} / ${rows.length}`}/><div className={`peg-challenges ${view}`}>{filtered.map(x=><article className={`peg-challenge ${x.locked?'locked':''}`} key={x.id}><header><span>{x.public_id||`#${String(x.id).padStart(3,'0')}`}</span><Difficulty value={x.difficulty}/></header><div><small>{x.category}</small><h2>{x.title}</h2><p>{x.description}</p></div><footer><strong>{x.points} PTS</strong>{x.locked?<span title="Selesaikan prerequisite">◈ Terkunci</span>:<Link to={`/pegasus/challenges/${x.id}`}>{x.status==='completed'?'Tinjau Solusi':x.status==='in_progress'?'Lanjutkan':'Mulai Challenge'} →</Link>}</footer></article>)}</div>{!filtered.length&&<State type="empty" message="Tidak ada challenge yang cocok. Coba hapus satu atau beberapa filter."/>}</>}</section>
}
