import React, { lazy, Suspense, useEffect, useState } from 'react'
import ReactDOM from 'react-dom/client'
import { BrowserRouter, Link, NavLink, Route, Routes, useLocation } from 'react-router-dom'
import Logo from './components/Logo'
import './styles.css'
const Home=lazy(()=>import('./pages/Home')); const Pegasus=lazy(()=>import('./pages/pegasus/Pegasus')); const About=lazy(()=>import('./pages/About')); const Services=lazy(()=>import('./pages/Services')); const Articles=lazy(()=>import('./pages/Articles')); const ArticleDetail=lazy(()=>import('./pages/ArticleDetail')); const CyberTools=lazy(()=>import('./pages/CyberTools')); const Contact=lazy(()=>import('./pages/Contact')); const NotFound=lazy(()=>import('./pages/NotFound'))
function MetaScroll(){const {pathname}=useLocation(); useEffect(()=>{window.scrollTo(0,0); const names={'/':'Xech Cyber Security','/about':'Tentang | Xech Cyber','/services':'Layanan | Xech Cyber','/articles':'Artikel | Xech Cyber','/cyber-tools':'Cyber Readiness Tools | Xech Cyber','/pegasus':'PEGASUS CTF | Xech Cyber','/contact':'Kontak | Xech Cyber'}; document.title=pathname.startsWith('/articles/')?'Tutorial Mitigasi CVE | Xech Cyber':pathname.startsWith('/pegasus')?'PEGASUS CTF | Xech Cyber':names[pathname]||'Halaman Tidak Ditemukan | Xech Cyber'},[pathname]); return null}
function App(){const [open,setOpen]=useState(false); const {pathname}=useLocation(); const isPegasus=pathname.startsWith('/pegasus'); return <><MetaScroll/><header><nav aria-label="Navigasi utama"><Logo/><button className="menu" aria-expanded={open} aria-controls="navlinks" onClick={()=>setOpen(!open)}>Menu</button><div id="navlinks" className={open?'navlinks open':'navlinks'}>{[['/','Home'],['/about','About'],['/services','Services'],['/articles','Artikel'],['/cyber-tools','Cyber Tools'],['/pegasus','PEGASUS CTF'],['/contact','Contact']].map(([to,n])=><NavLink key={to} to={to} end={to==='/'||to==='/articles'} onClick={()=>setOpen(false)}>{n}</NavLink>)}</div></nav></header><main className={isPegasus?'pegasus-main':undefined}><Suspense fallback={<p className="loading">Memuat…</p>}><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/services" element={<Services/>}/><Route path="/articles" element={<Articles/>}/><Route path="/articles/:slug" element={<ArticleDetail/>}/><Route path="/cyber-tools" element={<CyberTools/>}/><Route path="/pegasus/*" element={<Pegasus/>}/><Route path="/contact" element={<Contact/>}/><Route path="*" element={<NotFound/>}/></Routes></Suspense></main><footer><Logo/><div className="footer-links"><Link to="/articles">Artikel</Link><Link to="/cyber-tools">Cyber Tools</Link><Link to="/pegasus">PEGASUS CTF</Link><Link to="/contact">Kontak</Link></div><p>© 2026 Xech Cyber Security. All rights reserved.</p></footer></>}
ReactDOM.createRoot(document.getElementById('root')).render(<React.StrictMode><BrowserRouter><App/></BrowserRouter></React.StrictMode>)
