import React, { lazy, Suspense, useEffect, useState } from 'react'
import ReactDOM from 'react-dom/client'
import { BrowserRouter, Link, NavLink, Route, Routes, useLocation } from 'react-router-dom'
import Logo from './components/Logo'
import './styles.css'

const Journal=lazy(()=>import('./pages/Journal')); const Home=lazy(()=>import('./pages/Home')); const Pegasus=lazy(()=>import('./pages/pegasus/Pegasus')); const About=lazy(()=>import('./pages/About')); const Services=lazy(()=>import('./pages/Services')); const Articles=lazy(()=>import('./pages/Articles')); const ArticleDetail=lazy(()=>import('./pages/ArticleDetail')); const CyberTools=lazy(()=>import('./pages/CyberTools')); const Contact=lazy(()=>import('./pages/Contact')); const NotFound=lazy(()=>import('./pages/NotFound'))
const navItems=[['/','Home'],['/about','Tentang'],['/services','Layanan'],['/articles','Insight'],['/journal','Journal'],['/cyber-tools','Cyber Tools'],['/pegasus','PEGASUS CTF']]

function Icon({name}){const paths={menu:<><path d="M4 7h16M4 12h16M4 17h16"/></>,close:<><path d="m6 6 12 12M18 6 6 18"/></>,arrow:<><path d="M5 12h14M14 7l5 5-5 5"/></>};return <svg className="ui-icon" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>}
function MetaScroll(){const {pathname}=useLocation(); useEffect(()=>{window.scrollTo(0,0); const names={'/':'Xech Cyber Security','/about':'Tentang | Xech Cyber','/services':'Layanan | Xech Cyber','/articles':'Insight | Xech Cyber','/journal':'Journal | Xech Cyber','/cyber-tools':'Cyber Readiness Tools | Xech Cyber','/pegasus':'PEGASUS CTF | Xech Cyber','/contact':'Kontak | Xech Cyber'}; document.title=pathname.startsWith('/articles/')?'Tutorial Mitigasi CVE | Xech Cyber':pathname.startsWith('/pegasus')?'PEGASUS CTF | Xech Cyber':names[pathname]||'Halaman Tidak Ditemukan | Xech Cyber'},[pathname]); return null}
function Loading(){return <div className="loading-state" role="status" aria-label="Memuat halaman"><span className="skeleton wide"/><span className="skeleton title"/><span className="skeleton copy"/><span className="skeleton cards"/></div>}
function Shell(){const [open,setOpen]=useState(false);const {pathname}=useLocation();const isPegasus=pathname.startsWith('/pegasus');useEffect(()=>setOpen(false),[pathname]);return <><MetaScroll/><a className="skip-link" href="#main-content">Lewati ke konten utama</a><header className="site-header"><nav aria-label="Navigasi utama"><Logo/><div className="navlinks" data-open={open}>{navItems.map(([to,n])=><NavLink key={to} to={to} end={to==='/'||to==='/articles'}>{n}</NavLink>)}<Link className="nav-cta" to="/contact">Konsultasi <Icon name="arrow"/></Link></div><button className="menu" aria-expanded={open} aria-controls="navlinks" aria-label={open?'Tutup menu':'Buka menu'} onClick={()=>setOpen(!open)}><Icon name={open?'close':'menu'}/></button></nav></header><main id="main-content" className={isPegasus?'pegasus-main':undefined}><Suspense fallback={<Loading/>}><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/services" element={<Services/>}/><Route path="/articles" element={<Articles/>}/><Route path="/articles/:slug" element={<ArticleDetail/>}/><Route path="/journal" element={<Journal/>}/><Route path="/cyber-tools" element={<CyberTools/>}/><Route path="/pegasus/*" element={<Pegasus/>}/><Route path="/contact" element={<Contact/>}/><Route path="*" element={<NotFound/>}/></Routes></Suspense></main><footer><div className="footer-main"><div className="footer-brand"><Logo/><p>Mengubah kompleksitas keamanan siber menjadi keputusan yang jelas, terukur, dan dapat ditindaklanjuti.</p><span className="system-status"><i/> Sistem operasional</span></div><div><strong>Eksplorasi</strong><Link to="/services">Layanan</Link><Link to="/articles">Insight</Link><Link to="/journal">Journal</Link><Link to="/cyber-tools">Cyber Tools</Link></div><div><strong>Terhubung</strong><Link to="/about">Tentang kami</Link><Link to="/contact">Kontak</Link><a href="mailto:hello@xechcybersecurity.com">Email</a></div></div><div className="footer-bottom"><p>© 2026 Xech Cyber Security</p><p>Security, engineered with clarity.</p></div></footer></>}
ReactDOM.createRoot(document.getElementById('root')).render(<React.StrictMode><BrowserRouter><Shell/></BrowserRouter></React.StrictMode>)
